name: website

on:
  push:
    branches:
    - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - run: pip install flask Pillow requests pdoc typing_extensions && python -m pykinezumiko.conf -o _site
    - uses: actions/upload-pages-artifact@v1
      with:
        path: _site/
    - uses: actions/deploy-pages@v1
