name: website

on:
  push:
    branches:
    - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: astral-sh/setup-uv@main
    - run: |
        mkdir -p _site
        uv sync --locked --all-extras --dev
        uv run -m pykinezumiko.makedocs > _site/index.html
    - uses: actions/upload-pages-artifact@main
      with:
        path: _site/
    - uses: actions/deploy-pages@main
