name: website

on:
  push:
    branches:
    - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - id: cache
      uses: actions/cache@v3
      with:
        path: cache
        key: '114514'
    - run: |
        pipx install poetry
        mkdir -p _site
        poetry run python -m pykinezumiko.makedocs > _site/index.html
    - uses: actions/upload-pages-artifact@v1
      with:
        path: _site/
    - uses: actions/deploy-pages@v1
